#!/usr/bin/env ruby
require 'fileutils'
require 'shellwords'

IGNORED_FILES = %w{.DS_Store .. .}
FUZZ = "25%"

def add_background(source_dir, target_dir, color)
  if source_dir == target_dir
    puts "Hey fuckwit, you're gonna overwrite your source images"
  end

  # Make sure the target_dir exists target_dir
  FileUtils.mkdir_p target_dir

  all_files = Dir.entries(source_dir)
  images = all_files - IGNORED_FILES

  puts "Adding #{color} background to"
  images.each do |image_file|
    puts "    #{image_file}"
    image_path = Shellwords.escape("#{source_dir}/#{image_file}")
    destination_image = Shellwords.escape("#{target_dir}/#{image_file}")
    command = "convert #{image_path} -fill '#{color}' -fuzz #{FUZZ} -opaque none #{destination_image}"
    system(command)
  end
end

source_dir, target_dir, color = *ARGV
add_background(source_dir, target_dir, color)